### PR TITLE
Feature/prices

### PR DESCRIPTION
**Pull request by loadpixels**
Added initial draft of PricesAPI - implementing the V3 API Version of /prices/{EPIC}

new method added: 
```
async getPricesBetweenDates(
    epic: string,
    resolution: Resolution,
    startDate: Date,
    endDate: Date,
    pageSize: number = 0,
    pageNumber: number = 1
  ): Promise<HistoricalPricesResponse>
```

### CODE REVIEW

**Comment by bennycode** [comment]
That's a really great PR! Thank you so much for your contribution. Would you mind if we put `/prices/{EPIC}` to the existing `MarketAPI`? I would like to follow the categorization of: https://labs.ig.com/rest-trading-api-reference

**Screenshot**

image

**Comment by loadpixels** [comment]
Yeah, I'm happy to move it over. Will push a new commit later on. I might create it as a property of the market API (like market.prices.betweenDates....) , as I was thinking of having a few helper functions. What do you think?
  

  

    
  
  
>

**Comment by bennycode** [comment]
Sounds good to me. Will do the same then for `AccountAPI` and `DealingAPI`. 👍

**Comment by loadpixels** [comment]
I've moved the API to sit under the Markets API - i'm just wondering out loud whether it'd be a better design decision to create a Market class that is instantiated with an EPIC and then have methods to get the prices etc under it?

Something like;

```
const gpbusd = new Market('CS.D.GBPUSD.TODAY.IP');
let mood = gpbusd.igSentiment;
gbpusd.getPrices('HOUR_4', startDate, endDate);

// etc etc
```

Maybe it's adding complexity for little benefit - what are your thoughts?

**Comment by bennycode** [comment]
I think that's a bit too much mapping. In my opinion the "ig-trading-api" should just become a wrapper (written in TypeScript) around the IG Trading API. So I would like to merge your PR as it is now. Are you okay with that?

**Comment by loadpixels** [comment]
fair enough! 
Gimme a few minutes - i've just written an extra 'getPoints' method that just returns the requested number of points from now. Need to write the test -  I'll commit in a sec

**Comment by bennycode** [comment]
Ofcourse! Take your time. :)

**Comment by loadpixels** [comment]
dunno if Github notified you when i committed - but it's here now 👍

**Comment by bennycode** [comment]
Grrrreat! I merged your PR and applied some refactorings:

- Turned `InstrumentType` into an `enum`, so it can be reused
- Added TSDoc for `getPrices`
- Renamed `PricesAPI` to `PriceAPI` (`client.rest.market.price`), so it is consistent with the singular naming of the library
- Removed commented code
- Added an ESLint plugin to automatically sort keys of objects

If you are okay with that, I will create a new version of the library. Looking forward to your feedback. 🙂

**Comment by loadpixels** [comment]
Yep - that all makes sense to me 👍  thanks!

**Comment by bennycode** [comment]
Great, it has been released together with the dealing API in [v0.2.0](https://www.npmjs.com/package/ig-trading-api/v/0.2.0). I turned the `Date` parameters for `getPricesBetweenDates` into `strings` to avoid timezone conflicts when running in different environments (i.e. local dev environment & production hosting in another country).

**Pull request merged**
