### PR TITLE
Update to LoginAPI to remove creationSessionFromMobileLogin

### PR DESCRIPTION
**Pull request by Brookie144**
Updated LoginAPI login login function to use the createSession method instead of the createSessionFromMobileLogin method.

### CODE REVIEW

**Comment by bennycode** [comment]
Will this fix error #540?

**Comment by Brookie144** [comment]
Hi Benny, have tested and this fixes #540. I am now able to stream lightstreamer candle data with a live account.

**Comment by bennycode** [comment]
Hooray! Can you please fix the linting errors (just run `yarn fix`) and remove your changes to `.yarnrc` and `.yarn/releases/yarn-1.22.19.cjs`?

**Comment by Brookie144** [comment]
Thanks Benny, have ran yarn fix and removed the changes to the two yarn files.

**Comment by bennycode** [comment]
Thanks. What happens if you run `yarn test`? For me it shows:

> LoginAPI login selects the mobile login when using a live account

The test case and the `creationSessionFromMobileLogin` can probably removed now if no longer in use.

**Comment by Brookie144** [comment]
I get the same error. I will update the test case to remove the reference to the now removed `createSessionFromMobileLogin`

**Pull request merged**
