### PR TITLE
Feature/lightstreamer

### PR DESCRIPTION
**Pull request by loadpixels**
Added basic lightstreamer implementation to return CandleStick interface.

Test is exceptionally hacky due to lightstreamer and requires demo credentials on the environment to pass auth

### CODE REVIEW

**Comment by bennycode** [comment]
Oh, wow! This feature is on top of my wishlist. 🤩

How about making it accessible through `client.stream` (sounds more intuitive than `client.ls`)?

**Comment by loadpixels** [comment]
No problem! any suggestions on improving the tests?

**Comment by bennycode** [comment]
It looks like you are connecting to the "real / production" Lightstreamer API in `LightstreamerAPI.test.ts`? That needs to be faked / mocked. In my other project ([coinbase-pro-node](https://github.com/bennycode/coinbase-pro-node)), I had to mock a WebSocket server (wss). You can check how it is done to get an idea on how to fake the Lightstreamer server: https://github.com/bennycode/coinbase-pro-node/blob/v2.17.1/src/client/WebSocketClient.test.ts#L23

If that's too complicated, you can also create a mock object for the Lightstreamer endpoint. Here is how you can mock objects with the Jasmine test framework: https://derickbailey.com/2014/04/23/mock-objects-in-nodejs-tests-with-jasmine-spies/

**Comment by loadpixels** [comment]
I've been trying to read through what you suggested, I'm drawing a blank on the utility of mocking the object - surely you just end up testing a fake object and you don't test what you wrote? Same goes for the WS approach, you're just testing something else. What am I missing? Sorry if I'm missing the point.

**Comment by loadpixels** [comment]
realised that the test was requiring login to receive the the lightstreamer server and CST tokens etc - figured could nock it to return a public lightstream server and connect to that, given that the function invocation is already mocked

**Comment by bennycode** [comment]
That sounds very promising! But it means that the test still makes an outgoing request to the public internet in order to connect to the public lightstreamer (http://push.lightstreamer.com:80)? 

I would like the tests to run solely on localhost, without connections to external servers (as these 
cannot be controlled by our test case). 

Lightstreamer seems to offer a WebSocket server (plus fallbacks). In my "coinbase-pro-node" library, I spinned up a WebSocket server myself in the test. Can we do the same for the Lightstreamer tests here?

**Comment by loadpixels** [comment]
> Lightstreamer seems to offer a WebSocket server

I can't seem to find that - do you have a link? Lightstreamer Server is a Java application - it only has a node adapter that I can see

**Comment by bennycode** [comment]
I will merge your PR as is and fix it for you. :)

**Comment by bennycode** [comment]
It's released now with **ig-trading-api@0.5.0**. 😎

**Comment by beekeweerts** [comment]
@loadpixels I am trying to get the Candle data through the Lightstream endpoint, but unfortunately `onItemUpdate` is never called. In the Companion interface (https://labs.ig.com/sample-apps/streaming-companion/index.html) I get the error "Insufficient permissions". Could it be that you have to subscribe to get the live data (https://www.ig.com/en/help-and-support/cfds/fees-and-charges/what-are-your-charges-for-extra-services-like-live-data-feeds)? Or do you have another idea how I can prevent the "Insufficient permissions" error?

**Pull request merged**
